/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaclass02arraylist;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        int normalArray []={1,2,3,4,5};

        for(int count=0; count<normalArray.length; count++){
            System.out.println(normalArray[count]);
        }
        System.out.println("===========================");
        System.out.println("start printing from normal array with for each loop");
        for(int numberFromTheArray : normalArray){
            System.out.println(numberFromTheArray);
        }
        System.out.println("ending printing from normal array with for each loop");
        System.out.println("===========================");
        ArrayList<Integer> list=new ArrayList<>();

        list.add(1);
        list.add(2);
        list.add(3);
        list.add(4);
        list.add(5);
        //list.clear(); // this will clear the Array list

        // this will make a sublist form the original one it will take the element that in index 2 and stop at index 4 without the value inside it
        System.out.println("the sub array from the ArrayList: "+list.subList(2,4));
        for(int count=0; count<list.size(); count++){
            System.out.println(list.get(count));
        }
    }
}
