/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaclass02;

public class Library {


    public int add(int numberOne, int numberTwo) {

        return numberOne + numberTwo;
    }
}
