/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bulider.pattern;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
//        AnimalBuilder duck= new AnimalBuilder()
//                .setAge(5)
//                .setCanAdopted(true)
//                .build();


        Animal cat=new Elephant()
                .setAge(5)
                .build();

        Animal obj=new Cat()
                .setName("cat")
                .build();
    }
}
